//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3074.
// 
#pragma warning disable 1591

namespace Ec2Bootstrapperlib.Ec2FileUploadProxy {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Ec2FileUploadSoap", Namespace="http://tempuri.org/")]
    public partial class Ec2FileUpload : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback UploadAndInstallMsiFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInstallationStatusOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Ec2FileUpload() {
            this.Url = global::Ec2Bootstrapperlib.Properties.Settings.Default.Ec2Bootstrapperlib_Ec2FileUploadProxy_Ec2FileUpload;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UploadAndInstallMsiFileCompletedEventHandler UploadAndInstallMsiFileCompleted;
        
        /// <remarks/>
        public event GetInstallationStatusCompletedEventHandler GetInstallationStatusCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadAndInstallMsiFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UploadAndInstallMsiFile(string fileName, string encodedFile) {
            object[] results = this.Invoke("UploadAndInstallMsiFile", new object[] {
                        fileName,
                        encodedFile});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UploadAndInstallMsiFileAsync(string fileName, string encodedFile) {
            this.UploadAndInstallMsiFileAsync(fileName, encodedFile, null);
        }
        
        /// <remarks/>
        public void UploadAndInstallMsiFileAsync(string fileName, string encodedFile, object userState) {
            if ((this.UploadAndInstallMsiFileOperationCompleted == null)) {
                this.UploadAndInstallMsiFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadAndInstallMsiFileOperationCompleted);
            }
            this.InvokeAsync("UploadAndInstallMsiFile", new object[] {
                        fileName,
                        encodedFile}, this.UploadAndInstallMsiFileOperationCompleted, userState);
        }
        
        private void OnUploadAndInstallMsiFileOperationCompleted(object arg) {
            if ((this.UploadAndInstallMsiFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadAndInstallMsiFileCompleted(this, new UploadAndInstallMsiFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInstallationStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetInstallationStatus(string guid) {
            object[] results = this.Invoke("GetInstallationStatus", new object[] {
                        guid});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetInstallationStatusAsync(string guid) {
            this.GetInstallationStatusAsync(guid, null);
        }
        
        /// <remarks/>
        public void GetInstallationStatusAsync(string guid, object userState) {
            if ((this.GetInstallationStatusOperationCompleted == null)) {
                this.GetInstallationStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInstallationStatusOperationCompleted);
            }
            this.InvokeAsync("GetInstallationStatus", new object[] {
                        guid}, this.GetInstallationStatusOperationCompleted, userState);
        }
        
        private void OnGetInstallationStatusOperationCompleted(object arg) {
            if ((this.GetInstallationStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInstallationStatusCompleted(this, new GetInstallationStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void UploadAndInstallMsiFileCompletedEventHandler(object sender, UploadAndInstallMsiFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadAndInstallMsiFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadAndInstallMsiFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetInstallationStatusCompletedEventHandler(object sender, GetInstallationStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInstallationStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInstallationStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591